/*****************************************************************************
 * Eliot
 * Copyright (C) 2007-2012 Olivier Teulière
 * Authors: Olivier Teulière <ipkiss @@ gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *****************************************************************************/

#include <algorithm>
#include <cstdlib>
#include <filesystem>
#include <format>
#include <fstream>
#include <memory>
#include <string>
#include <string_view>
#include <system_error>

#ifdef WIN32
#   include <windows.h>
#   include <shlobj.h>
#endif

#include <toml++/toml.hpp>

#include "config.h"

#include "settings.h"
#include "debug.h"
#include "game_exception.h"


INIT_LOGGER(game, Settings);


Settings *Settings::m_instance = nullptr;


Settings & Settings::Instance()
{
    if (m_instance == nullptr)
    {
        m_instance = new Settings;
    }
    return *m_instance;
}


void Settings::Destroy()
{
    delete m_instance;
    m_instance = nullptr;
}


std::filesystem::path Settings::GetConfigFileDir()
{
    std::filesystem::path dirPath;
#ifdef WIN32
    wchar_t szPath[MAX_PATH];
    // Get the AppData directory
    if (SHGetFolderPathW(NULL, CSIDL_APPDATA | CSIDL_FLAG_CREATE, NULL, 0, szPath) == S_OK)
    {
        dirPath = szPath;
        dirPath /= "eliot";
    }
#else
    // Follow the XDG Base Directory Specification (from freedesktop.org)
    // XXX: In fact we don't follow it to the letter, because the location
    // of the config file could be different when reading and writing.
    // But in the case of Eliot it's not very important (we don't try to
    // merge config files)...
    const char *configDir = std::getenv("XDG_CONFIG_HOME");
    if (configDir && configDir[0] != '\0')
        dirPath = configDir;
    else
    {
        const char *homeDir = std::getenv("HOME");
        if (homeDir && homeDir[0] != '\0')
        {
            dirPath = std::filesystem::path(homeDir) / ".config";
        }
    }

    if (!dirPath.empty())
        dirPath /= "eliot";
#endif

    // Try to create the directory if it doesn't exist.
    // If the directory cannot be created, saving the
    // configuration file will definitely fail...
    if (!dirPath.empty())
    {
        std::error_code ec;
        std::filesystem::create_directories(dirPath, ec);
    }

    return dirPath;
}


namespace
{
    /**
     * Here is a sample file generated by libconfig:
training :
{
  search-limit = 100;
};
duplicate :
{
  solo-players = 16;
  solo-value = 10;
  reject-invalid = true;
};
freegame :
{
  reject-invalid = true;
};
arbitration :
{
  fill-rack = true;
  solo-auto = true;
  solo-players = 16;
  solo-value = 10;
  penalty-value = 5;
  warnings-limit = 3;
  search-limit = 100;
};
topping :
{
  elapsed-penalty = true;
  timeout-penalty = 60;
};
     */
    void parseLegacyCfg(const std::filesystem::path& path, toml::table& outTable)
    {
        std::ifstream file(path);
        if (!file.is_open())
            return;

        // Lambda to strip all formatting delimiters specific to libconfig syntax
        // (whitespaces, semicolons, quotes, assignments, and block braces)
        const auto cleanFunc = [](std::string_view sv) {
            std::string s;
            for (char c : sv)
                if (!std::isspace(c) && !std::string_view(";\"=:{}").contains(c)) s += c;
            return s;
        };

        std::string line, currentGroup;
        while (std::getline(file, line))
        {
            std::string_view lv = line;
            // Remove leading whitespaces
            if (size_t first = lv.find_first_not_of(" \t\r\n"); first != std::string_view::npos)
                lv = lv.substr(first);
            else
                continue;

            // Ignore comments
            if (lv.starts_with('#') || lv.starts_with("//"))
                continue;

            // Start of a group
            // This assumes no nesting of groups, which is the case for us.
            if (size_t colonPos = lv.find(':'); colonPos != std::string_view::npos)
            {
                currentGroup = cleanFunc(lv.substr(0, colonPos));
                continue;
            }

            // Variable assignments
            if (size_t eqPos = lv.find('='); eqPos != std::string_view::npos && !currentGroup.empty())
            {
                auto key = cleanFunc(lv.substr(0, eqPos));
                auto val = cleanFunc(lv.substr(eqPos + 1));
                if (key.empty() || val.empty()) continue;

                auto& section = *outTable[currentGroup].as_table();

                if (val == "true" || val == "TRUE")
                    section.insert_or_assign(key, true);
                else if (val == "false" || val == "FALSE")
                    section.insert_or_assign(key, false);
                else {
                    // XXX: a  bit ugly...
                    try {
                        section.insert_or_assign(key, std::stoi(val));
                    } catch(...) {
                        section.insert_or_assign(key, val);
                    }
                }
            }
        }
    }
}


Settings::Settings()
{
    m_conf = std::make_unique<toml::table>(toml::table{
        // ============== Training mode options ==============
        { "training", toml::table{
            // Number of search results kept in a search
            { "search-limit", 100 }
        }},
        // ============== Duplicate mode options ==============
        { "duplicate", toml::table{
            // Minimum number of players in a duplicate game needed to apply
            // a "solo" bonus (16 is the ODS value)
            { "solo-players", 16 },
            // Number of points granted for a solo (10 is the ODS value)
            { "solo-value", 10 },
            // If true, Eliot complains when the player does something illegal
            // If false, the word is accepted (with a score of 0) and the
            // player does not get a second chance
            { "reject-invalid", true }
        }},
        // ============== Freegame mode options ==============
        { "freegame", toml::table{
            // If true, Eliot complains when the player does something illegal
            // If false, the word is accepted (with a score of 0) and the
            // player does not get a second chance.
            // Trying to change letters or to pass the turn in an incorrect way
            // will be rejected in any case.
            { "reject-invalid", true }
        }},
        // ============== Arbitration mode options ==============
        { "arbitration", toml::table{
            // If true, a random rack is defined, otherwise the rack is left untouched
            { "fill-rack", true },
            // If true, solos are automatically given when appropriate
            // If false, the arbitrator has full control (but must do everything manually)
            { "solo-auto", true },
            // Minimum number of players in a duplicate game needed to apply a "solo" bonus
            // (16 is the ODS value)
            { "solo-players", 16 },
            // Number of points granted for a solo (10 is the ODS value)
            { "solo-value", 10 },
            // Default value of a penalty
            { "penalty-value", 5 },
            // Maximum number of warnings before getting penalties
            { "warnings-limit", 3 },
            // Number of search results kept in a search
            { "search-limit", 100 }
        }},
        // ============== Topping mode options ==============
        { "topping", toml::table{
            // If true, a score penalty equal to the number of elapsed seconds
            // is given to the player at each turn
            { "elapsed-penalty", true },
            // Additional penalty points given to the player when the timer expires
            { "timeout-penalty", 60 }
        }}
    });

    auto configDir = GetConfigFileDir();
    m_fileName = configDir / "eliot.toml";

    // Before Eliot 2.3, we used libconfig++ to store settings.
    // It was causing multiple problems (poor CMake support, needs patching
    // for Windows cross-compilation), so we now use toml++ instead.
    // To avoid breaking users, we still provide a simple hand-made parser
    // for the old configuration file, which we directly convert to toml
    // and delete.
    std::filesystem::path legacyFile = configDir / "eliot.cfg";

    if (std::filesystem::exists(m_fileName))
    {
        try
        {
            toml::table parsed = toml::parse_file(m_fileName.string());
            for (auto&& [section, node] : parsed)
            {
                if (node.is_table() && (*m_conf)[section].is_table())
                {
                    for (auto&& [key, value] : *node.as_table())
                        (*m_conf)[section].as_table()->insert_or_assign(key, value);
                }
            }
        }
        catch (const toml::parse_error& e)
        {
            LOG_ERROR("Error parsing TOML config file: {}\n", e.what());
        }
    }
    else if (std::filesystem::exists(legacyFile))
    {
        try
        {
            parseLegacyCfg(legacyFile, *m_conf);
            save();
            std::filesystem::remove(legacyFile);
        }
        catch (const std::exception& e)
        {
            LOG_ERROR("Error migrating legacy config text: {}\n", e.what());
        }
    }
}


Settings::~Settings() = default;


void Settings::save() const
{
    std::ofstream outFile(m_fileName, std::ios::out | std::ios::trunc);
    if (!outFile)
    {
        throw GameException(
            std::format("The configuration file cannot be written ({})", m_fileName.string()));
    }
    outFile << *m_conf;
}


void Settings::setBool(const std::string &iName, bool iValue)
{
    setValue<bool>(iName, iValue);
}


bool Settings::getBool(const std::string &iName) const
{
    if (auto node = m_conf->at_path(iName))
    {
        if (auto val = node.as_boolean())
            return val->get();
    }
    throw GameException("No such option: " + iName);
}


void Settings::setInt(const std::string &iName, int iValue)
{
    setValue<int>(iName, iValue);
}


int Settings::getInt(const std::string &iName) const
{
    if (auto node = m_conf->at_path(iName))
    {
        if (auto val = node.as_integer())
            return static_cast<int>(val->get());
    }
    throw GameException("No such option: " + iName);
}


template<class T>
requires std::same_as<T, int> || std::same_as<T, bool>
void Settings::setValue(const std::string &iName, T iValue)
{
    if (auto node = m_conf->at_path(iName))
    {
        if constexpr (std::is_same_v<T, bool>)
        {
            if (auto active = node.as_boolean()) { *active = iValue; return; }
        }
        else // T is guaranteed to be 'int' by the requires clause
        {
            if (auto active = node.as_integer()) { *active = iValue; return; }
        }
    }
#ifdef DEBUG
    throw GameException("No such option: " + iName);
#endif
}

