set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TOOLCHAIN_PREFIX "x86_64-w64-mingw32")
set(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}-clang")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}-clang++")
set(CMAKE_RC_COMPILER "${TOOLCHAIN_PREFIX}-windres")

# Force targeting system flags straight into the compiler core properties
# Needed for the zlib build, at least
set(CMAKE_C_FLAGS "-target x86_64-w64-windows-gnu -D_WIN32_WINNT=0x0A00 -D_WIN32_WINNT_WIN10=0x0A00" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "-target x86_64-w64-windows-gnu -D_WIN32_WINNT=0x0A00 -D_WIN32_WINNT_WIN10=0x0A00" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_EXE_LINKER_FLAGS "-static" CACHE STRING "" FORCE)

