name: Linux build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build:
    runs-on: ubuntu-26.04

    env:
      # Instruct vcpkg to read/write from its default local path
      VCPKG_BINARY_SOURCES: "default,readwrite"

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Install host toolchain dependencies
      # First apt install for gperf
      # Second one for libxcrypt
      # Third one for qtbase
      # Third one for eliot's build (without dependencies)
      run: |
        sudo apt update
        sudo apt install -y autoconf autoconf-archive automake libtool
        sudo apt install -y libltdl-dev
        sudo apt install -y libx11-dev libx11-xcb-dev libxcb-res0-dev libxcb-xinput-dev \
            libxkbcommon-dev libxkbcommon-x11-dev libxcb-image0-dev libxcb-keysyms1-dev \
            libxcb-icccm4-dev libxcb-render-util0-dev libxcb-cursor-dev \
            libgl1-mesa-dev libegl1-mesa-dev libdbus-1-dev libxi-dev libxrender-dev
        sudo apt install -y clang-21 cmake ninja-build

    # Set up caching
    - name: Set up binary cache storage
      uses: actions/cache@v6
      with:
        path: ~/.cache/vcpkg/archives
        key: ${{ runner.os }}-vcpkg-cache-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-cache-

    - name: Bootstrap vcpkg and install dependencies
      uses: lukka/run-vcpkg@v11
      with:
        # Do not build for vcpkg.json, we will do it with CMake's manifest mode
        runVcpkgInstall: false

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_C_COMPILER=clang-21 \
          -DCMAKE_CXX_COMPILER=clang++-21 \
          -DVCPKG_TARGET_TRIPLET=x64-linux-release \
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/extras/cmake/vcpkg-linux.toolchain.cmake \
          -DENABLE_QT6=OFF

    - name: Compile
      run: cmake --build build --parallel $(nproc)

