name: Linux build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build:
    runs-on: ubuntu-26.04

    env:
      # Instruct vcpkg to read/write from its default local path
      VCPKG_BINARY_SOURCES: "default,readwrite"

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Install host toolchain dependencies
      # First apt install for gperf
      # Second one for libxcrypt
      # Third one for qtbase
      # Fourth one is for eliot's build (without dependencies)
      run: |
        sudo apt update
        sudo apt install -y autoconf autoconf-archive automake libtool
        sudo apt install -y libltdl-dev
        sudo apt install -y libx11-dev libx11-xcb-dev \
            libxkbcommon-dev libxkbcommon-x11-dev \
            libgl1-mesa-dev libegl1-mesa-dev libdbus-1-dev libxi-dev \
            '^libxcb.*-dev' libxrender-dev libglu1-mesa-dev libsm-dev libice-dev
        sudo apt install -y gettext clang-21 cmake ninja-build

    # Set up caching
    - name: Set up binary cache storage
      uses: actions/cache@v6
      with:
        path: ~/.cache/vcpkg/archives
        key: ${{ runner.os }}-vcpkg-cache-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-cache-

    - name: Bootstrap vcpkg and install dependencies
      uses: lukka/run-vcpkg@v11
      with:
        # Do not build for vcpkg.json, we will do it with CMake's manifest mode
        runVcpkgInstall: false

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_C_COMPILER=clang-21 \
          -DCMAKE_CXX_COMPILER=clang++-21 \
          -DVCPKG_TARGET_TRIPLET=x64-linux-release \
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/extras/cmake/vcpkg-linux.toolchain.cmake

    - name: Compile
      run: cmake --build build --parallel $(nproc)


  windows-cross-build:
    runs-on: ubuntu-26.04
    env:
      VCPKG_BINARY_SOURCES: "default,readwrite"
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Install build systems
      # First apt install for gperf
      # Second one is for eliot's build (without dependencies)
      run: |
        sudo apt update
        sudo apt install -y autoconf autoconf-archive automake libtool
        sudo apt install -y gettext cmake ninja-build

    - name: Setup LLVM-MinGW Toolchain
      run: |
        mkdir -p /opt/llvm-mingw
        curl -L https://github.com/mstorsjo/llvm-mingw/releases/download/20260826/llvm-mingw-20260826-ucrt-ubuntu-22.04-x86_64.tar.xz | tar -xJ --strip-components=1 -C /opt/llvm-mingw
        echo "/opt/llvm-mingw/bin" >> $GITHUB_PATH

    - name: Set up binary cache storage
      uses: actions/cache@v6
      with:
        path: ~/.cache/vcpkg/archives
        key: ${{ runner.os }}-vcpkg-win-cache-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-win-cache-

    - name: Bootstrap vcpkg and install dependencies
      uses: lukka/run-vcpkg@v11
      id: runvcpkg
      with:
        runVcpkgInstall: false

    - name: Configure CMake
      run: |
        export VCPKG_ROOT="${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}"
        cmake -B vcpkg-win32 -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/extras/cmake/vcpkg-windows.toolchain.cmake \
          -D_WIN32_WINNT=0x0A00

    - name: Compile
      run: cmake --build vcpkg-win32 --parallel $(nproc)
